version: '3'
services:
  cms:
    build:
      context: ./cms
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    container_name: loquijs-cms
    stdin_open: true
    volumes:
       - ./cms:/usr/src
       - /cms/node_modules
       - /cms/.next